name = "Parsa Hugo"
license = "MIT"
licenselink = "https://github.com/animemandir/parsa-hugo/blob/master/LICENSE"
description = "Parsa is a personal blog theme powered by Hugo. It also can be used for portfolio website."
homepage = "https://viptoons"
demosite = "https://viptoons.netlify.app"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.62.2"

[author]
  name = "animemandir"
  homepage = "https://www.animezia.com/"
